# Generated by Django 3.1.3 on 2020-12-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img',
            options={'verbose_name_plural': '图片表'},
        ),
        migrations.AlterField(
            model_name='img',
            name='src',
            field=models.FileField(max_length=32, upload_to='', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='img',
            name='summary',
            field=models.CharField(max_length=128, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='img',
            name='title',
            field=models.CharField(max_length=16, verbose_name='标题'),
        ),
    ]
