# Generated by Django 3.1.3 on 2020-12-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20201207_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='src',
            field=models.FileField(max_length=32, upload_to='static/img/', verbose_name='图片路径'),
        ),
    ]
